spring.application.name=finstream-server
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
etl.python.executable=${PYTHON_EXECUTABLE:python3}
etl.script.path=${ETL_SCRIPT_PATH:/app/etl-python/etl_pipeline.py}
spring.jpa.hibernate.ddl-auto=validate